env = Environment()

env['APP_TARGET'] = 'NibbalApp'
env['APP_SOURCES'] = ['NibbalApp.cpp', 'PParams.cpp', 'KinectPlayer.cpp']
env['ASSETS'] = ['models']

env = SConscript('../../../blocks/Cinder-Assimp/scons/SConscript', exports = 'env')

env = SConscript('../../../blocks/Cinder-NI/scons/SConscript', exports = 'env')

SConscript('../../../scons/SConscript', exports = 'env')
